<?php

namespace Events\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DeletedNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeletedNotificationRepository extends EntityRepository
{
}
