app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /

fos_user:
    resource: "@UserBundle/Resources/config/routing.yml"

oauth:
    resource: "@AppBundle/Resources/config/oauth/routing.yml"
    prefix:  /oauth